COLUMNS:

  year: int64  
  month: object 
  day: object 
  extended: int64  
  state: object 
  city:  object
  target_type: object
  nationality: object 
  weapon_type: object 

TARGET_COLUMN:

  name: attack_type