COLUMNS:

  State: object 
  multilingual_literacy: float64
  literacy: float64 
  university_admission: float64 
  sanitation: float64
  electricity: float64
  state_unemployment: float64
  avg_household_size: float64
  region_population_size: float64
  drinking_water: float64
  month: int64  
  day: int64  
  isweekday: int64  
  is_holiday: int64   
TARGET_COLUMN:

  name: is_attack